#!/bin/bash
# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.
#
# Generate daily status report for the MsQuic repository
# This script can be run manually or by GitHub Actions

set -e

OUTPUT_FILE="${1:-status_report.md}"
REPO="${GITHUB_REPOSITORY:-NikolajBjorner/msquic}"

echo "Generating daily status report..."
echo ""

# Initialize report file
> "$OUTPUT_FILE"

# Add header
REPORT_DATE=$(date -u '+%Y-%m-%d %H:%M UTC')
cat >> "$OUTPUT_FILE" << EOF
# 📊 MsQuic Daily Status Report

**Generated:** $REPORT_DATE
**Repository:** $REPO

---

EOF

# File Statistics
echo "### File Statistics" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
C_FILES=$(find src -name '*.c' -o -name '*.cpp' -o -name '*.h' 2>/dev/null | wc -l || echo "0")
PS_FILES=$(find scripts -name '*.ps1' 2>/dev/null | wc -l || echo "0")
CMAKE_FILES=$(find . -name 'CMakeLists.txt' -o -name '*.cmake' 2>/dev/null | wc -l || echo "0")
echo "- C/C++ files: $C_FILES" >> "$OUTPUT_FILE"
echo "- PowerShell scripts: $PS_FILES" >> "$OUTPUT_FILE"
echo "- CMake files: $CMAKE_FILES" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Recent Commit Activity
echo "### Recent Commit Activity (Last 24 Hours)" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
COMMIT_COUNT=$(git log --since="24 hours ago" --oneline 2>/dev/null | wc -l || echo "0")
echo "- Commits in last 24 hours: $COMMIT_COUNT" >> "$OUTPUT_FILE"

if [ "$COMMIT_COUNT" -gt 0 ]; then
  echo "" >> "$OUTPUT_FILE"
  echo "Recent commits:" >> "$OUTPUT_FILE"
  echo '```' >> "$OUTPUT_FILE"
  git log --since="24 hours ago" --oneline --no-decorate | head -10 >> "$OUTPUT_FILE"
  echo '```' >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Branch information
echo "### Branch Information" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
CURRENT_BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
echo "- Current branch: \`$CURRENT_BRANCH\`" >> "$OUTPUT_FILE"
BRANCH_COUNT=$(git branch -a 2>/dev/null | wc -l || echo "0")
echo "- Total branches: $BRANCH_COUNT" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Last commit info
echo "### Latest Commit" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
if git log -1 --format="%H" &>/dev/null; then
  LAST_COMMIT_HASH=$(git log -1 --format="%h")
  LAST_COMMIT_AUTHOR=$(git log -1 --format="%an")
  LAST_COMMIT_DATE=$(git log -1 --format="%ar")
  LAST_COMMIT_MESSAGE=$(git log -1 --format="%s")
  
  echo "- **Commit:** \`$LAST_COMMIT_HASH\`" >> "$OUTPUT_FILE"
  echo "- **Author:** $LAST_COMMIT_AUTHOR" >> "$OUTPUT_FILE"
  echo "- **Date:** $LAST_COMMIT_DATE" >> "$OUTPUT_FILE"
  echo "- **Message:** $LAST_COMMIT_MESSAGE" >> "$OUTPUT_FILE"
fi
echo "" >> "$OUTPUT_FILE"

# Add footer
cat >> "$OUTPUT_FILE" << EOF

---

*This report was generated by the daily status script.*
*For more information, see \`scripts/generate-daily-status.sh\`*
EOF

echo "Report generated successfully: $OUTPUT_FILE"
echo ""
echo "Preview:"
echo "========================================="
cat "$OUTPUT_FILE"
echo "========================================="
